/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBand: typeof import('./components/form/AddBand.vue')['default']
    AddEvent: typeof import('./components/form/AddEvent.vue')['default']
    AddPlace: typeof import('./components/form/AddPlace.vue')['default']
    BandList: typeof import('./components/main/BandList.vue')['default']
    DeleteBand: typeof import('./components/form/DeleteBand.vue')['default']
    DeleteEvent: typeof import('./components/form/DeleteEvent.vue')['default']
    DeletePlace: typeof import('./components/form/DeletePlace.vue')['default']
    EditBand: typeof import('./components/form/EditBand.vue')['default']
    EditEvent: typeof import('./components/form/EditEvent.vue')['default']
    EditPlace: typeof import('./components/form/EditPlace.vue')['default']
    EventList: typeof import('./components/main/EventList.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    PlaceList: typeof import('./components/main/PlaceList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
